version: '3.8'

services:
  # PHP service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/symfony

  # Nginx service
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/symfony
    depends_on:
      - php

  # MariaDB service for main database
  database:
    image: mariadb:11.1.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: asdf123
    ports:
      - "33066:3306"
    volumes:
      - database_data:/var/lib/mysql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']

  # MariaDB service for test database
  test_database:
    image: mariadb:11.1.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_test
      MYSQL_USER: app
      MYSQL_PASSWORD: asdf123
    ports:
      - "3307:3306"
    volumes:
      - test_database_data:/var/lib/mysql
      - ./docker/mariadb/init-test.sql:/docker-entrypoint-initdb.d/init-test.sql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']

volumes:
  database_data:
  test_database_data: 